### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by motinados** [motinados/xlsx-kaku#1]
Mostly, I analyze xlsx files created with Online Excel and write code to produce similar outputs. 

Consequently, there's a high likelihood that my current code might encounter limitations in the future, necessitating substantial changes in specifications.

Here the tasks.
Tasks will be added as I become familiar with Excel.

## features
- [x] cell for number
- [x] cell for string
- [x]  style
- [x] cell for date
- [x] cell for hyperlink
- [x] cell for boolean
- [x] cell for formula
- [x] workbook
- [x] multi worksheets
- [x] merge cells
- [x] alignment
- [x] freeze panes
- [x] column style
- [x] row style
- [x] default col width
- [x] default row height
- [x] internal hyperlink
- [x] email hyperlink
- [x] conditional formatting
- [ ] auto filter
- [x] adding image (one cell anchor)
- [ ]  adding image (two cell anchor)
- [ ] theme
- [ ] table
.
.
.
- [ ] adding chart

## modules
- [x] merge cells module
- [x] conditional formatting module
- [x] adding image module

## documents
- [ ] documents
- [ ] samples

## improve UX
- [ ] type inference
- [ ] json to xlsx

To be continued...

**Comment by motinados** [comment]
I took a look at the sample xlsx for the chart, but it seems incredibly complicated.

**Comment by motinados** [comment]
Feature support status is documented in the README, and any future work will be tracked in separate issues as needed.
